const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike slim shirt',
      category: 'Shirts',
      image: '../images/p1.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '../images/p2.jpeg',
      price: 140,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Shirts',
      image: '../images/p5.jpeg',
      price: 156,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Fit Pants',
      slug: 'nike-fit-pants',
      category: 'Pants',
      image: '../images/p4.jpeg',
      price: 120,
      countInStock: 15,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    // {
    //   _id: "5",
    //   name: "Nike Slim Pant",
    //   category: "Pants",
    //   image: "../images/p5.jpeg",
    //   price: 110,
    //   countInStock: 13,
    //   brand: "Nike",
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: "high quality product",
    // },
    // {
    //   _id: "6",
    //   name: "Nike Slim Pant",
    //   category: "Pants",
    //   image: "../images/p6.jpeg",
    //   price: 130,
    //   countInStock: 12,
    //   brand: "Puma",
    //   rating: 4.5,
    //   numReviews: 15,
    //   description: "high quality product",
    // },
  ],
};

export default data;
